### PR TITLE
Fix types

### LINKED ISSUE #887: Invalid next.config.js options detected
`next-translate`: 1.5.0
`next`: 12.2.3

i18n.js
```
const hoistNonReactStatics = require('hoist-non-react-statics');

module.exports = {
  locales: ['en', 'nl'],
  defaultLocale: 'en',
  pages: {
    '*': ['common'],
  },
  loadLocaleFrom: async (lang) => {
    const commonTranslations = await import('translations');
    const appTranslations = await import('./src/translations/');

    return new Promise((resolve) =>
      resolve({ ...commonTranslations[lang], ...appTranslations[lang] })
    );
  },
  defaultNS: 'common',
  staticsHoc: hoistNonReactStatics, // required for loading custom layouts with translations
};
```

next.config.js
```
/** @type {import('next').NextConfig} */

const nextTranslate = require('next-translate');
const withTM = require('next-transpile-modules')([
  'components',
  'hooks',
]);

const nextConfig = {
  reactStrictMode: true,
};


module.exports = withTM(nextTranslate(nextConfig));

```

Whenever I run my app, I get following warning on my console. How can I fix this?
```
warn  - Invalid next.config.js options detected: 
[
  {
    "instancePath": "/i18n",
    "schemaPath": "#/properties/i18n/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "loadLocaleFrom"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "/i18n",
    "schemaPath": "#/properties/i18n/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "defaultNS"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "/i18n",
    "schemaPath": "#/properties/i18n/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "staticsHoc"
    },
    "message": "must NOT have additional properties"
  }
] 
```

Is there something wrong with how I have configured things?

### PR DESCRIPTION
**Pull request by Dragate**
- Improve config loader using `NextConfig`,`I18nConfig` types
- Add missing `pagesInDir` to `I18nConfig` type 
- Fixes #887

### CODE REVIEW

File: src/plugin/index.ts [hunk 1]
```diff
@@ -50,11 +51,10 @@ export default function nextTranslate(nextConfig: any = {}) {
     ...nextConfig,
     i18n: {
       ...i18n,
-      ...restI18n,
```
Comment (aralroca) [inline src/plugin/index.ts:53]: this should not be deleted. What should be done is to remove the restI18n properties that are next-translate properties and not i18n properties. That is, make sure that everything in restI18n are properties of i18n's Next.js.

Comment (Dragate) [reply src/plugin/index.ts:53]: > this should not be deleted. What should be done is to remove the restI18n properties that are next-translate properties and not i18n properties. That is, make sure that everything in restI18n are properties of i18n's Next.js.

`restI18n` has no properties that are valid for Next.js.

image

Comment (aralroca) [reply src/plugin/index.ts:53]: Many people use the `i18n.js` file to put all the features of Next-translate and Next.js, to have it together in one place. The thing is that here we should remove the Next-translate ones so that only the Next.js ones are passed.

Comment (Dragate) [reply src/plugin/index.ts:53]: I see now. Never realised that next.js properties could be declared in next-translate, even though the plugin has no use for them. I'll update the PR soon enough.

**Review by aralroca — APPROVED** [review]
thank you very much for your contribution!

**Comment by aralroca** [comment]
@all-contributors please add @Dragate for code
